version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Asia/Tokyo
    groups:
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "20:00"
      timezone: Asia/Tokyo
