name: Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install

      - name: Fetch TLE data
        run: curl 'https://celestrak.org/NORAD/elements/gp.php?GROUP=last-30-days&FORMAT=tle' -o src/satellites.txt

      - run: pnpm run build:app

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: app

  deploy:
    needs: build-app

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        id: deployment
